### ISSUE TITLE
Corriger

### ISSUE THREAD

**Issue by gabays** [Masculinites-Esclavagistes/MEGV-FR-MSS-18#1]
Attention le lien n'est plus le bon

https://github.com/Masculinites-Esclavagistes/MEGV-FR-MSS-18/blob/f189ae1ab0435495fa7926017f8c10c078fe44da/citations.cff#L26

https://github.com/Masculinites-Esclavagistes/MEGV-FR-MSS-18/blob/f189ae1ab0435495fa7926017f8c10c078fe44da/htr-united.yml#L121

https://github.com/Masculinites-Esclavagistes/MEGV-FR-MSS-18/blob/f189ae1ab0435495fa7926017f8c10c078fe44da/htr-united.yml#L143

https://github.com/Masculinites-Esclavagistes/MEGV-FR-MSS-18/blob/f189ae1ab0435495fa7926017f8c10c078fe44da/htr-united.yml#L145

**Comment by Marion-phi** [comment]
Je viens de le mettre à jour, merci.

**Comment by Marion-phi** [comment]
Je viens de le mettre à jour, merci !
